package com.travmahrajvar.bringmefood;

import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import android.widget.Toast;

import static android.content.Context.CLIPBOARD_SERVICE;

/**
 * Created by Travis on 11/12/17.
 */

public class GettingFoodFragment_SessionInfo extends Fragment {
	// TODO: Rename parameter arguments, choose names that match
	// the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
	private static final String ARG_SESSION_KEY = "key";
	private static final String ARG_SESSION_RESTAURANT = "restaurant";
	private static final String ARG_SESSION_LOCATION = "location";
	
	// TODO: Rename and change types of parameters
	private String sessionKey;
	private String sessionRestaurant;
	private String sessionLocation;
	
	private OnFragmentInteractionListener mListener;
	
	public GettingFoodFragment_SessionInfo() {
		// Required empty public constructor
	}
	
	/**
	 * Creates a new SessionInfo fragment for the GettingFood activity PageViewer.
	 * (Automatically generated by Android Studio using a new blank fragment.)
	 *
	 * @param key Current session key.
	 * @param restaurant Current session restaurant.
	 * @param location Current session location.
	 * @return A new instance of fragment GettingFoodFragment_SessionInfo.
	 */
	// TODO: Rename and change types and number of parameters
	public static GettingFoodFragment_SessionInfo newInstance(String key, String restaurant, String location) {
		GettingFoodFragment_SessionInfo fragment = new GettingFoodFragment_SessionInfo();
		Bundle args = new Bundle();
		args.putString(ARG_SESSION_KEY, key);
		args.putString(ARG_SESSION_RESTAURANT, restaurant);
		args.putString(ARG_SESSION_LOCATION, location);
		fragment.setArguments(args);
		return fragment;
	}
	
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		if (getArguments() != null) {
			sessionKey = getArguments().getString(ARG_SESSION_KEY);
			sessionRestaurant = getArguments().getString(ARG_SESSION_RESTAURANT);
			sessionLocation = getArguments().getString(ARG_SESSION_LOCATION);
			
//			((TextView)getView().findViewById(R.id.txtSessionDestination))
//					.setText(getString(R.string.gettingFood_sessionInfo_label2, sessionRestaurant, sessionLocation));
//
//			((TextView)getView().findViewById(R.id.txtSessionCode))
//					.setText(sessionKey);
		}
	}
	
	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
	                         Bundle savedInstanceState) {
		// Inflate the layout for this fragment
		View root = inflater.inflate(R.layout.fragment_getting_food_sessioninfo, container, false);
		
		Bundle args = getArguments();
		sessionKey = args.getString(ARG_SESSION_KEY);
		sessionRestaurant = args.getString(ARG_SESSION_RESTAURANT);
		sessionLocation = args.getString(ARG_SESSION_LOCATION);
		
		//Set labels
		((TextView)root.findViewById(R.id.txtSessionDestination))
				.setText(getString(R.string.gettingFood_sessionInfo_label2, sessionRestaurant, sessionLocation));
		((TextView)root.findViewById(R.id.txtSessionCode))
				.setText(sessionKey);
		
		return root;
	}
	
	// TODO: Rename method, update argument and hook method into UI event
	public void onButtonPressed(Uri uri) {
		if (mListener != null) {
			mListener.onFragmentInteraction(uri);
		}
	}
	
	@Override
	public void onAttach(Context context) {
		super.onAttach(context);
		if (context instanceof OnFragmentInteractionListener) {
			mListener = (OnFragmentInteractionListener) context;
		} else {
			throw new RuntimeException(context.toString()
					+ " must implement OnFragmentInteractionListener");
		}
	}
	
	@Override
	public void onDetach() {
		super.onDetach();
		mListener = null;
	}
	
	/**
	 * This interface must be implemented by activities that contain this
	 * fragment to allow an interaction in this fragment to be communicated
	 * to the activity and potentially other fragments contained in that
	 * activity.
	 * <p>
	 * See the Android Training lesson <a href=
	 * "http://developer.android.com/training/basics/fragments/communicating.html"
	 * >Communicating with Other Fragments</a> for more information.
	 */
	public interface OnFragmentInteractionListener {
		// TODO: Update argument type and name
		void onFragmentInteraction(Uri uri);
	}
}
