package com.travmahrajvar.bringmefood;

import android.content.ClipData;
import android.content.ClipboardManager;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import android.widget.Toast;

import static android.content.Context.CLIPBOARD_SERVICE;

/**
 * (Automatically generated by Android Studio)
 *
 * A simple {@link Fragment} subclass.
 * Activities that contain this fragment must implement the
 * {@link GettingFoodFragment_PendingUsers.OnFragmentInteractionListener} interface
 * to handle interaction events.
 * Use the {@link GettingFoodFragment_PendingUsers#newInstance} factory method to
 * create an instance of this fragment.
 */
public class GettingFoodFragment_SessionInfo extends Fragment {
	//Argument names for the incoming intents
	private static final String ARG_SESSION_KEY = "key";
	private static final String ARG_SESSION_RESTAURANT = "restaurant";
	private static final String ARG_SESSION_LOCATION = "location";
	
	//The arguments themselves
	private String sessionKey;
	private String sessionRestaurant;
	private String sessionLocation;
	
	public GettingFoodFragment_SessionInfo() {
		// Required empty public constructor
	}
	
	/**
	 * Creates a new SessionInfo fragment for the GettingFood activity PageViewer.
	 * (Automatically generated by Android Studio using a new blank fragment.)
	 *
	 * @param key Current session key.
	 * @param restaurant Current session restaurant.
	 * @param location Current session location.
	 * @return A new instance of fragment GettingFoodFragment_SessionInfo.
	 */
	// TODO: Rename and change types and number of parameters
	public static GettingFoodFragment_SessionInfo newInstance(String key, String restaurant, String location) {
		GettingFoodFragment_SessionInfo fragment = new GettingFoodFragment_SessionInfo();
		
		//Get the intent extras and put them into arguments
		Bundle args = new Bundle();
		args.putString(ARG_SESSION_KEY, key);
		args.putString(ARG_SESSION_RESTAURANT, restaurant);
		args.putString(ARG_SESSION_LOCATION, location);
		fragment.setArguments(args);
		
		//Return the new fragment
		return fragment;
	}
	
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		if (getArguments() != null) { //Get and set the arguments
			sessionKey = getArguments().getString(ARG_SESSION_KEY);
			sessionRestaurant = getArguments().getString(ARG_SESSION_RESTAURANT);
			sessionLocation = getArguments().getString(ARG_SESSION_LOCATION);
		}
	}
	
	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
	                         Bundle savedInstanceState) {
		// Inflate the layout for this fragment
		View root = inflater.inflate(R.layout.fragment_getting_food_sessioninfo, container, false);
		
		//Get the arguments from the parent activity
		Bundle args = getArguments();
		sessionKey = args.getString(ARG_SESSION_KEY);
		sessionRestaurant = args.getString(ARG_SESSION_RESTAURANT);
		sessionLocation = args.getString(ARG_SESSION_LOCATION);
		
		//Set labels
		((TextView)root.findViewById(R.id.txtSessionDestination))
				.setText(getString(R.string.gettingFood_sessionInfo_label2, sessionRestaurant, sessionLocation));
		((TextView)root.findViewById(R.id.txtSessionCode))
				.setText(sessionKey);
		
		return root;
	}
	
	@Override
	public void onAttach(Context context) {
		super.onAttach(context);
		if (!(context instanceof OnFragmentInteractionListener)) {
			throw new RuntimeException(context.toString()
					+ " must implement OnFragmentInteractionListener");
		}
	}
	
	@Override
	public void onDetach() {
		super.onDetach();
	}
	
	/**
	 * This interface must be implemented by activities that contain this
	 * fragment to allow an interaction in this fragment to be communicated
	 * to the activity and potentially other fragments contained in that
	 * activity.
	 * <p>
	 * See the Android Training lesson <a href=
	 * "http://developer.android.com/training/basics/fragments/communicating.html"
	 * >Communicating with Other Fragments</a> for more information.
	 */
	public interface OnFragmentInteractionListener {
		// TODO: Update argument type and name
		void onFragmentInteraction(Uri uri);
	}
}
